services:
    - name: authz
      url: http://demo-server:8888/
      credentials:
        bearer:
          token: "bGFza2RqZmxha3NkamZsa2Fqc2Rsa2ZqYWtsc2RqZmtramRmYWxkc2tm"
  
  discovery:
    name: /example/discovery
  
  labels:
    region: "UK"