---
services:
  - name: example_bundle
    url: http://demo-server:8888/
    credentials:
      bearer:
        token: "bGFza2RqZmxha3NkamZsa2Fqc2Rsa2ZqYWtsc2RqZmtramRmYWxkc2tm"

labels:
  app: myapp
  environment: production

bundles:
  authz:
    service: example_bundle
    resource: bundle/rbac.tar.gz
    polling:
      # do not polling bundle too frequently
      min_delay_seconds: 300
      max_delay_seconds: 600

decision_logs:
  service: example_bundle
  partition_name: bundle
  reporting:
    # upload log gzip more frequently
    min_delay_seconds: 30
    max_delay_seconds: 60

status:
  service: example_bundle
  partition_name: bundle

default_decision: rbac/allow
