services:
    example_rbac:
      url: http://media.newbmiao.com/opa/
      credentials:
        bearer:
          token: "bGFza2RqZmxha3NkamZsa2Fqc2Rsa2ZqYWtsc2RqZmtramRmYWxkc2tm"
  
labels:
    app: myapp
    environment: production
  
bundles:
    authz:
        service: example_rbac
        resource: bundle/rbac.tar.gz
        polling:
        min_delay_seconds: 60
        max_delay_seconds: 120
  
decision_logs:
    console: true
  
status:
    console: true
  
default_decision: /example_rbac/allow