global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
  
rule_files:
  - ./rules/*.yml

scrape_configs:
  - job_name: "opa-bundle"
    metrics_path: "/metrics"
    static_configs:
    - targets: ["opa-bundle:8181"]

  - job_name: "opa-discovery"
    metrics_path: "/metrics"
    static_configs:
    - targets: ["opa-discovery:8182"]

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 8s
    static_configs:
    - targets: ['node-exporter:9100']