global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "opa-bundle"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["opa-bundle:8181"]

  - job_name: "opa-discovery"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["opa-discovery:8182"]