name: opa-koans
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Shell Lint
        run: sh scripts/shellLint.sh
      - name: Yaml Lint
        run: sh scripts/yamlLint.sh
      - name: Rego Lint
        run: sh scripts/regoLint.sh
      - name: Rego Test
        run: sh scripts/regoTest.sh
      - name: Bundle Verify
        run: sh scripts/bundleVerify.sh
